apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-deployment
  namespace: default
  labels:
    app: trend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-app
  template:
    metadata:
      labels:
        app: trend-app
    spec:
      containers:
      - name: trend-container
        image: vigneshvicky229/trend-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port
